services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: packing-list
      POSTGRES_USER: packing-list
      POSTGRES_PASSWORD: packing-list
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
